### ISSUE TITLE
Synonymes match de différents clades

### ISSUE THREAD

**Issue by vincent-beauregard-ielab** [ReseauBiodiversiteQuebec/bdqc_taxa#10]
Exemple de Salix, match avec des animaux et avec des Plantes.

**Comment by vincent-beauregard-ielab** [comment]
Fixed with optional arguments in method `TaxaRef.from_all_sources()` :

From updated README.md : 

> ### Conflicts
> 
> Certain scientific names corresponds to different organism within two entirely different branches of the tree of life. For example, the scientific name *Salix* corresponds to the genus of willows in the plant kingdom and to a genus of tunicates in the animal kingdom. To avoid matching for such case, the user can specify a parent taxa name to restrict the results to the branch containing the parent taxa. For example, the user can specify the parent taxa name *Plantae* to restrict the results to the plant kingdom.
> 
> The `parent_taxa` argument is optional. If not specified, the module will return all results for the given scientific name.

```python
from bdqc_taxa.taxa_ref import TaxaRef

results = TaxaRef.from_all_sources('Salix', parent_taxa='Plantae')
```

Next steps will be to update atlas-db and coleo-db ressources to allow the usage of this optionnal parameter.

https://github.com/ReseauBiodiversiteQuebec/atlas-db/issues/105
https://github.com/ReseauBiodiversiteQuebec/Coleo_DB/issues/127

**Comment by vcameron1** [comment]
Final step will be to add `parent_taxa_name` to all taxa names that match with multiple organisms
